### ISSUE TITLE
Add package to conda-forge?

### ISSUE THREAD

**Issue by arunkannawadi** [jundymek/free-proxy#19]
We use `fp` as a dependency in [`scholarly`](http://github.com/scholarly-python-package/scholarly) and we are considering making `scholarly` available in conda-forge. To do that, we need to get all our dependencies also in conda-forge and `fp` is the only one that is not in. As a part of this effort, could I raise a PR to get `fp` into `conda-forge` as well?

**Comment by giswqs** [comment]
I have created the `meta.yaml` file (using `conda skeleton pypi free-proxy`) need for the pull request to https://github.com/conda-forge/staged-recipes/pulls. The only thing needs to be changed is the line (recipe-maintainers). 

Related issue: https://github.com/scholarly-python-package/scholarly/issues/377

```
{% set name = "free-proxy" %}
{% set version = "1.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59d07ae697267ea032e3173ff7f3213a3f5fccf6cc7f4d4a6ca7ab259463fe48

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >= 3.6
  run:
    - lxml
    - python >= 3.6
    - requests

test:
  imports:
    - fp

about:
  home: https://github.com/jundymek/free-proxy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Proxy scraper for further use"
  doc_url: https://github.com/jundymek/free-proxy
  dev_url: https://github.com/jundymek/free-proxy

extra:
  recipe-maintainers:
    - your-github-id-here
```
